env_name: 'Breakout-v4'

rl_algo: 1

parallel: False

logdir: '/xrl/relogs/'

video_steps: 100
exp_name: 'breakout-no-feedback2'

seed: 12382

train:
  gamma: 0.9
  learning_rate: 0.0001

  num_episodes: 15000
  max_steps: 100000
  
  log_steps: 25
  save_every: 100
  
  feedback_alpha: 0
  feedback_delta: 0

  entropy_alpha: 0.0

  hidden_layer_size: 200