env_name: 'Bowling-v4'

rl_algo: 1

parallel: False

logdir: '/xrl/relogs/'

video_steps: 100

train:
  random_action_p: 0.05
  gamma: 0.97
  learning_rate: 0.0001

  num_episodes: 50000
  max_steps: 50000
  
  log_steps: 25
  # save every is for episodes
  save_every: 100