env_name: 'PongDeterministic-v4'

rl_algo: 1

parallel: False

logdir: '/xrl/relogs/'

video_steps: 100
exp_name: 'pong-feedback3'

seed: 28312

train:
  gamma: 0.9
  learning_rate: 0.001

  num_episodes: 20000
  max_steps: 100000
  
  log_steps: 25
  save_every: 100

  feedback_alpha: 1
  feedback_delta: 0

  entropy_alpha: 0.01

  hidden_layer_size: 200